// This file is generated by scripts/generate-site-routes.mjs.
// Add a page under app/**/page.tsx, then run npm run generate:routes.

export type SiteRoute = {
  label: string;
  href: string;
  detail: string;
  dynamic: boolean;
};

export const siteRoutes = [
  {
    "label": "Home",
    "href": "/",
    "detail": "Page · /",
    "dynamic": false
  },
  {
    "label": "About",
    "href": "/about",
    "detail": "Page · /about",
    "dynamic": false
  },
  {
    "label": "Contact",
    "href": "/contact",
    "detail": "Page · /contact",
    "dynamic": false
  },
  {
    "label": "Help",
    "href": "/help",
    "detail": "Page · /help",
    "dynamic": false
  },
  {
    "label": "Projects",
    "href": "/projects",
    "detail": "Page · /projects",
    "dynamic": false
  },
  {
    "label": "Slug",
    "href": "/projects/[slug]",
    "detail": "Page · /projects/[slug]",
    "dynamic": true
  },
  {
    "label": "Settings",
    "href": "/settings",
    "detail": "Page · /settings",
    "dynamic": false
  },
  {
    "label": "Writing",
    "href": "/writing",
    "detail": "Page · /writing",
    "dynamic": false
  },
  {
    "label": "Blogs",
    "href": "/writing/blogs",
    "detail": "Page · /writing/blogs",
    "dynamic": false
  },
  {
    "label": "Slug",
    "href": "/writing/blogs/[slug]",
    "detail": "Page · /writing/blogs/[slug]",
    "dynamic": true
  },
  {
    "label": "Essays",
    "href": "/writing/essays",
    "detail": "Page · /writing/essays",
    "dynamic": false
  },
  {
    "label": "Slug",
    "href": "/writing/essays/[slug]",
    "detail": "Page · /writing/essays/[slug]",
    "dynamic": true
  },
  {
    "label": "Notes",
    "href": "/writing/notes",
    "detail": "Page · /writing/notes",
    "dynamic": false
  },
  {
    "label": "Slug",
    "href": "/writing/notes/[slug]",
    "detail": "Page · /writing/notes/[slug]",
    "dynamic": true
  }
] as const satisfies readonly SiteRoute[];
